---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-log
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: learning-log
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: learning-log
        image: nygelsregistry.azurecr.io/learning-log:v6
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: learning-log
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: learning-log
